# Continous Integration Scrip
# Clinica - ARAMIS
#
# TODO:
#   - [ ] Test dataset
#   - [ ] Doc generation
#   - [ ] Automatize pipeline CL tests
#   - [ ] Automatize pipeline CL options tests

stages:
  - build
  - install
  - test
  - deploy

    #variables:
    #  BIDS_TEST: "/localdrive10TB/data/gitlab-runner/BIDS_TEST"
    #  CAPS_TEST: "/localdrive10TB/data/gitlab-runner/CAPS_TEST"
    #  WD_TEST: "/localdrive10TB/data/gitlab-runner/WD_TEST"
    #  ENVIRONMENT_TEST: "/export/applications/clinica/Ubuntu14.04/dot_path"

before_script:
  - pwd

after_script:
  - conda env remove --name clinica_env

create_environment:
  # Install python dependencies for  Clinica 
  stage: build
  tags:
    - install
  script:
    - conda env create -f environment.yml
    - source activate clinica_env
    - pip install -e .
    - eval "$(register-python-argcomplete clinica)"
    - clinica --help
    - source deactivate
  
#install_clinica:
#  stage: install
#  tags:
#    - install
#  script:
#    - source activate clinica_env
#    - clinica --help
#    - source deactivate
