# Continous Integration Scrip
# Clinica - ARAMIS
#
stages:
  - build
  - install
  - test
  - deploy

    #variables:
    #  BIDS_TEST: "/localdrive10TB/data/gitlab-runner/BIDS_TEST"
    #  CAPS_TEST: "/localdrive10TB/data/gitlab-runner/CAPS_TEST"
    #  WD_TEST: "/localdrive10TB/data/gitlab-runner/WD_TEST"
    #  ENVIRONMENT_TEST: "/export/applications/clinica/Ubuntu14.04/dot_path"

before_script:
  - pwd

after_script:
  - conda env remove -y  --name clinica_env

create_environment_macOS_sierra:
  # Install python dependencies for  Clinica 
  stage: build
  tags:
    - install
    - macOS
  script:
    - conda env create -f environment.yml
    - source activate clinica_env
    - pip install -e .
    - eval "$(register-python-argcomplete clinica)"
    - clinica --help
    - source deactivate
  

create_environment_linux_ubuntu:
  # Install python dependencies for  Clinica 
  stage: build
  tags:
    - install
    - linux
  script:
    - echo $SHELL
    - echo $PATH
    - conda env create -f environment.yml
    - source activate clinica_env
    - pip install -e .
    - eval "$(register-python-argcomplete clinica)"
    - clinica --help
    - source deactivate
#install_clinica:
#  stage: install
#  tags:
#    - install
#  script:
#    - source activate clinica_env
#    - clinica --help
#    - source deactivate
