# Continous Integration Scrip
# Clinica - ARAMIS
#
stages:
  - build
  - install
  - test
  - package 

    #variables:
    #  BIDS_TEST: "/localdrive10TB/data/gitlab-runner/BIDS_TEST"
    #  CAPS_TEST: "/localdrive10TB/data/gitlab-runner/CAPS_TEST"
    #  WD_TEST: "/localdrive10TB/data/gitlab-runner/WD_TEST"
    #  ENVIRONMENT_TEST: "/export/applications/clinica/Ubuntu14.04/dot_path"

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/

before_script:
  - pwd
after_script:
  #  - conda env remove -y  --name clinica_env

build:mac:
  stage: build
  tags:
    - macOS
  script:
    # If the environment already exists or if it's changed
    # (by editing the environment.yml file), the environment
    # is recreated.
    - >
      if conda env list|grep -w "clinica_env"; then
        if git diff HEAD~ --name-only|grep environment.yml; then
          echo "REcreate environment clinica_env"
          conda env create --force --file environment.yml
        fi;
      else
        echo "Create environment clinica_env"
        conda env create --force --file environment.yml
      fi;

build:linux:
  stage: build
  tags:
    - linux
  script:
    # If the environment already exists or if it's changed
    # (by editing the environment.yml file), the environment
    # is recreated.
    - >
      if conda env list|grep -w "clinica_env"; then
        if git diff HEAD~ --name-only|grep environment.yml; then
          echo "REcreate environment clinica_env"
          conda env create --force --file environment.yml
        fi;
      else
        echo "Create environment clinica_env"
        conda env create --force --file environment.yml
      fi;

install:mac:
  # Install python dependencies for  Clinica 
  stage: install 
  tags:
    - install
    - macOS
  script:
    - source activate clinica_env
    - pip install .
    - eval "$(register-python-argcomplete clinica)"
    - clinica --help
    - source deactivate
  

install:linux:
  # Install python dependencies for  Clinica 
  stage: install
  tags:
    - install
    - linux
  script:
    - source activate clinica_env
    - pip install .
    - eval "$(register-python-argcomplete clinica)"
    - clinica --help
    - source deactivate

test_install:linux:
  stage: test
  tags:
    - linux
  script:
    - source activate clinica_env
    - clinica --help
    - source deactivate

test_install:mac:
  stage: test
  tags:
    - macOS
  script:
    - source activate clinica_env
    - clinica --help
    - source deactivate

pkg:
  stage: package
  tags:
    - macOS
  script:
    - tar -cvzf --exclude='.gitignore' --exclude='.git' --exclude='.DS_Store' --exclude='.gitmodules' --exclude='.idea' --exclude='.vscode' --exclude='.gitlab-ci.yml' -f clinica-$CI_COMMIT_REF_NAME.tar.gz  ./*
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - clinica-$CI_COMMIT_REF_NAME.tar.gz
  only:
    - tags
