# Continous Integration Scrip
# Clinica - ARAMIS
#
stages:
  - install
  - test
  - deploy

    #variables:
    #  BIDS_TEST: "/localdrive10TB/data/gitlab-runner/BIDS_TEST"
    #  CAPS_TEST: "/localdrive10TB/data/gitlab-runner/CAPS_TEST"
    #  WD_TEST: "/localdrive10TB/data/gitlab-runner/WD_TEST"
    #  ENVIRONMENT_TEST: "/export/applications/clinica/Ubuntu14.04/dot_path"

before_script:
  - pwd
  - conda env create -f environment.yml
after_script:
  - conda env remove -y  --name clinica_env

install_mac:
  # Install python dependencies for  Clinica 
  stage: build
  tags:
    - install
    - macOS
  script:
    - source activate clinica_env
    - pip install -e .
    - eval "$(register-python-argcomplete clinica)"
    - clinica --help
    - source deactivate
  

install_linux:
  # Install python dependencies for  Clinica 
  stage: build
  tags:
    - install
    - linux
  script:
    - source activate clinica_env
    - pip install -e .
    - eval "$(register-python-argcomplete clinica)"
    - clinica --help
    - source deactivate

test_spm_full_prep_mac:
  stage: test
  tag:
    - macOS
  script:
    - source activate clinica_env
    - clinica --help
    - source deactivate

